import { GatewayMode } from '../types/enums.js'

const HELP_TOPICS: Record<string, string> = {
  catalog: [
    'catalog.search(query, { k, limit, serverId, risk, tags, requiredArgs, detail })',
    '  query: natural language search for tools',
    '  k: number of results (default 5)',
    '  limit: compatibility alias for k; prefer k in new code',
    '  serverId: exact downstream server ID filter',
    '  risk: filter by risk level (Low, Medium, High)',
    '  tags: filter by capability tags',
    '  requiredArgs: keep only tools whose required args include all listed fields',
    '  detail: name | summary | signature | full',
    '  detail=summary returns handle, name, summary, risk',
    '  detail=signature adds args, required, and a short properties map (type/description/enum when available)',
    '  detail=full adds description and inputSchema',
    'catalog.list({ serverId, risk, tags, requiredArgs, limit, detail })',
    '  limit: max results',
    'catalog.describe(handle, { detail, fields })',
    '  handle: tool handle from search/list results',
    '  detail: name | summary | signature | full',
    '  handles are session-scoped and short-lived; use the handle returned in the current execution',
    '',
    'Example:',
    '  const tools = await catalog.search("fastmcp docs", { serverId: "fastmcp", requiredArgs: ["query"], detail: "signature", k: 3 })',
    '  const details = await catalog.describe(tools[0].handle, { detail: "signature" })',
    '  // details.properties.query.type, details.required, details.acceptsAdditionalProperties',
  ].join('\n'),
  mcp: [
    'mcp.call(handle, args)',
    '  handle: tool handle from catalog.search() or catalog.list()',
    '  do not invent handles like server:name; use the exact handle returned in this session',
    '  args: tool-specific arguments object',
    'mcp.batch([{ handle, args }, ...])',
    '  Execute multiple tool calls in parallel',
    '  Batch does not validate schema compatibility across handles; filter by requiredArgs or inspect signatures first',
    '',
    'Example:',
    '  const tools = await catalog.search("fastmcp docs", { serverId: "fastmcp", requiredArgs: ["query"], detail: "signature", k: 2 })',
    '  if (tools.length < 2) return { error: "not-enough-tools", count: tools.length, tools }',
    '  const rows = await mcp.batch([',
    '    { handle: tools[0].handle, args: { query: "quickstart" } },',
    '    { handle: tools[1].handle, args: { query: "installation" } },',
    '  ])',
  ].join('\n'),
  result: [
    'result.pick(value, fields)',
    '  Extract specific fields from objects',
    'result.limit(array, n)',
    '  Return first n items from an array',
    '  If a tool returns { content: [...] }, pass out.content instead of out',
    'result.items(value)',
    '  Return value.content when present, or value itself if already an array',
    'result.text(value)',
    '  Concatenate text blocks from value.content or return the string itself',
    'result.count(value)',
    '  Count items in array or object keys',
    'result.groupBy(array, field)',
    '  Group array items by field value',
    'result.grep(array, field, pattern)',
    '  Filter by field matching regex pattern',
    'result.flatten(array, depth)',
    '  Flatten nested arrays',
    'result.summarize(value)',
    '  Generate concise summary of any value',
    '',
    'Example:',
    '  return result.limit(result.pick(rows, ["number", "title", "state"]), 10)',
    '  const out = await mcp.call(tool.handle, { query: "quickstart" })',
    '  return result.limit(out.content, 1)',
    '  return result.text(out)',
  ].join('\n'),
  artifacts: [
    'artifacts.save(data, { label })',
    '  Save data for later reference (use for large results)',
    '  label: optional human-readable label',
    'artifacts.list()',
    '  List all saved artifacts in this session',
    '',
    'Large results should be saved and referenced instead of returned in full.',
  ].join('\n'),
}

const MODE_GUIDANCE: Record<string, string[]> = {
  [GatewayMode.Default]: [
    '',
    '═══════════════════════════════════════════════════════════',
    'DEFAULT MODE — Use the published downstream tools directly',
    '═══════════════════════════════════════════════════════════',
    '',
    '1. DISCOVER: Tools are already visible in the session window',
    '2. CALL: Invoke the tool name directly with its arguments',
    '3. NO WRAPPERS: gateway_search_tools / gateway_call_tool are not used',
  ],
  [GatewayMode.Compat]: [
    '',
    '═══════════════════════════════════════════════════════════',
    'COMPAT MODE — Use gateway_search_tools and gateway_call_tool',
    '═══════════════════════════════════════════════════════════',
    '',
    '1. DISCOVER TOOLS: Use gateway_search_tools with a query',
    '   Example: gateway_search_tools({ query: "github issues" })',
    '',
    '2. CALL TOOLS: Use gateway_call_tool with the exact name and serverId from search results',
    '   Example: gateway_call_tool({',
    '     name: "list_issues",',
    '     serverId: "github",',
    '     arguments: { owner: "org", repo: "repo" }',
    '   })',
    '',
    '3. TOOL IDENTIFIERS: Always use the exact name and serverId returned by gateway_search_tools',
    '',
    'ERROR RECOVERY: If a tool call fails, try:',
    '  - Check name and serverId match gateway_search_tools output exactly',
    '  - Verify arguments match the published tool schema',
    '  - Retry with simplified arguments',
  ],
  [GatewayMode.Code]: [
    '',
    '═══════════════════════════════════════════════════════════',
    'CODE MODE — Use gateway_run_code with runtime APIs',
    '═══════════════════════════════════════════════════════════',
    '',
    '1. DISCOVER: catalog.search() or catalog.list()',
    '   Returns tool handles for use with mcp.call()',
    '',
    '2. EXECUTE: mcp.call(handle, args) or mcp.batch([...])',
    '   Execute discovered tools with arguments',
    '   For batch, prefer handles filtered by requiredArgs or confirmed with catalog.describe()',
    '',
    '3. SHAPE: result.* functions to transform output',
    '   pick(), limit(), items(), text(), grep(), groupBy(), summarize()',
    '',
    '4. RETURN: Simple expressions can be sent without return, for example `1 + 1`',
    '   Multi-line snippets should use `return` for the final value',
    '   `result` is reserved by the runtime and should not be redeclared',
    '   Return serializable data; if needed, normalize with JSON.parse(JSON.stringify(value))',
    '   Use result.limit() to keep responses small',
    '   For large data, use artifacts.save() instead',
    '',
    'ERROR RECOVERY: If execution fails, check:',
    '  - Tool handle exists: await catalog.search("name")',
    '  - Handle freshness: re-run catalog.search() or catalog.list() in the same session',
    '  - Args match signature: await catalog.describe(handle, { detail: "signature" })',
    '  - Text-only tool output: use result.text(out) or result.items(out)',
    '  - Batch compatibility: use catalog.search(..., { requiredArgs: ["field"] }) before mcp.batch(...)',
    '  - Async/await: Always await mcp.call() and catalog.*()',
    '  - Serialization: prefer result.pick()/result.limit() for complex tool outputs',
  ],
}

const COMMON_ERRORS = [
  '',
  '═══════════════════════════════════════════════════════════',
  'COMMON ERRORS AND RECOVERY',
  '═══════════════════════════════════════════════════════════',
  '',
  '• "Tool not found": Use catalog.search() to find correct handle',
  '• "Unknown tool handle": Handles are session-scoped; rediscover it with catalog.search() or catalog.list()',
  '• "Invalid arguments": Check catalog.describe() for expected args; for batch, make sure all handles accept the same arg shape',
  '• "Cannot read properties of undefined (reading handle)": Your script indexed a missing result; check tools.length, increase k, or relax filters',
  '• "Permission denied": Contact admin to enable tool for namespace',
  '• "Rate limited": Wait and retry with fewer requests (use mcp.batch)',
  '• "Connection failed": Downstream server may be unavailable',
  '• "`result` is reserved": Rename your local variable to `rows`, `out`, or `data`',
  '• "Could not be serialized": Return JSON-friendly data or use JSON.parse(JSON.stringify(value))',
]

export function buildGatewayHelp(
  topic?: string,
  gatewayMode: GatewayMode = GatewayMode.Code
): { topic: string; text: string } {
  const modeHeader = [
    '─────────────────────────────────────────────────────────────',
    `Active Mode: ${gatewayMode}`,
    '─────────────────────────────────────────────────────────────',
  ].join('\n')

  const modeSection = MODE_GUIDANCE[gatewayMode]?.join('\n') ?? ''

  if (!topic || topic === 'all') {
    return {
      topic: 'all',
      text: [
        modeHeader,
        '',
        'gateway_run_code runtime API',
        '',
        HELP_TOPICS['catalog'],
        '',
        HELP_TOPICS['mcp'],
        '',
        HELP_TOPICS['result'],
        '',
        HELP_TOPICS['artifacts'],
        modeSection,
        ...COMMON_ERRORS,
      ].join('\n'),
    }
  }

  return {
    topic,
    text: [modeHeader, HELP_TOPICS[topic] ?? HELP_TOPICS['catalog'], modeSection].join('\n'),
  }
}
